# docker-compose -f ./docker/docker-compose-test.yaml up --build
# docker-compose -f ./docker/docker-compose-test.yaml down

version: "2.4"
x-net: &net
  networks:
      - main
services:
  db:
    <<: *net
    image: datajoint/mysql:5.7
    container_name: workflow-miniscope-test-db
    environment:
      - MYSQL_ROOT_PASSWORD=simple
  workflow:
    <<: *net
    build:
      context: ../../
      dockerfile: ./workflow-miniscope/docker/Dockerfile.test
    env_file: .env
    image: workflow-miniscope-test:0.1.0
    container_name: workflow-miniscope-test
    environment:
      - DJ_HOST=db
      - DJ_USER=root
      - DJ_PASS=simple
      - MINISCOPE_ROOT_DATA_DIR=/main/test_data
      - DATABASE_PREFIX=test_
    command:
      - bash
      - -c
      - |
        echo "------ INTEGRATION TESTS ------"
        pytest -sv --cov-report term-missing --cov=workflow_miniscope -p no:warnings tests/
        tail -f /dev/null
    volumes:
      - ${TEST_DATA_DIR}:/main/test_data
      - ./apt_requirements.txt:/tmp/apt_requirements.txt
      - ../../element-lab:/main/element-lab
      - ../../element-animal:/main/element-animal
      - ../../element-session:/main/element-session
      - ../../element-interface:/main/element-interface
      - ../../element-miniscope:/main/element-miniscope
      - ..:/main/workflow-miniscope
    depends_on:
      db:
        condition: service_healthy
networks:
  main: